# Generated by Django 5.0.1 on 2024-01-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=180),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default='https://e7.pngegg.com/pngimages/577/649/png-clipart-question-mark-question-mark-thumbnail.png', null=True),
        ),
    ]
